### ISSUE TITLE
Tweaks 

### ISSUE THREAD

**Issue by ChurchOfTheSubgenius** [commune-os/website#1]
Here's a list of changes I'd like:

- Dark theme by default.
- The theme toggle animation is slow and unnecessary, just toggle the theme instantly. 
- Use the `Inter` font from the [commune.sh](https://github.com/commune-os/commune.sh) repo. It's also on google fonts but better to include it in the repo itself and have sveltekit/cloudflare cache it.
- The main logo on the top-left corner is super high-res. Use a much smaller sized `.svg` instead, preferably embedded in the html.
- Include the `.png` version of the logo in the `<meta>` so that it shows up when the site is linked.
- The favicon is missing.
- Change the main action button to link to the instance at `app.commune.sh`. 
- The large logo on the right is redundant, so maybe we'll replace that with a mockup of the app when I make then. I guess leave it there for now.

**Comment by harshmangalam** [comment]
Done
